[speech]
lang = "ja-JP"
speaking_rate = 1.5
pitch = 1.5
text_max = 256
credentials = ""
play_cmd = ["mpg123"]

[log]
debug = false
log = "stderr"
err_log = "stderr"

[pushbullet]
access_token = ""

[http]
addr = ":9001"
